SonarSource/docker-sonarqube

- 4.5.4/Dockerfile
- 5.1/Dockerfile
To see progress of downloading during build.
> Make progress of build more verbose

- recipes.md
With this recipe, you can restart sonarqube (or postgresql) without loosing data and upgrade or install some plugins.
> Recipe for plugins

- 4.5.6/Dockerfile
- 5.1.2/Dockerfile
- 5.2/Dockerfile
- 5.3/Dockerfile
See also docker-library/official-images#1420.
> Fix "gpg" usage to stop relying on deprecated and insecure behavior

- recipes.md
Also fixed issue with database data not being persisted for some versions of Docker.
> Updated Docker Compose configuration to version 2.

- 5.6.3-alpine/Dockerfile
- 5.6.3/Dockerfile
- 6.1-alpine/Dockerfile
- 6.1/Dockerfile
> expose conf and logs directory as docker volume

- build-and-run.sh
Change 'reqired' to 'required' in build-and-run.sh
This closes #307
> Fix wrong english

- .travis.yml
this is not a good fix as this version will also be purged in a couple of weeks
but 
1. there is no quick and more permanent fix
2. a sprint on this repository should come quick and will be able to think of one such better fix
> upgrade SQ to 8.0.0.28930

- .travis.yml
- 8/community/run.sh
- 8/developer/run.sh
- 8/enterprise/run.sh
This should resolve issue #325 
This workaround is not needed anymore since SonarQube issue SONAR-12344 has been fixed in version 8.0.0.29057
> [#325] remove untracked tail process in run.sh

- .travis.yml
> update SQ version to include docker flag in system info

- develop.md
> Update developer documentation with new 8.0 images

- 8/community/Dockerfile
- 8/community/run.sh
- 8/community/sonar.sh
- 8/developer/Dockerfile
- 8/developer/run.sh
- 8/developer/sonar.sh
- 8/enterprise/Dockerfile
- 8/enterprise/run.sh
- 8/enterprise/sonar.sh
- example-compose-files/sq-with-h2/docker-compose.yml
- example-compose-files/sq-with-postgres/docker-compose.yml
- examples.md
- switch base image to alpine
- allow running the image as an arbitrary user
- support running the image in read-only mode (when using volumes)
> SONAR-13182 switch to alpine

- 8/community/Dockerfile
- 8/developer/Dockerfile
- 8/enterprise/Dockerfile
> SonarQube 8.3.1

- 8/community/Dockerfile
- 8/developer/Dockerfile
- 8/enterprise/Dockerfile
> Upgrade version to 8.4.1

- 8/community/Dockerfile
- 8/developer/Dockerfile
- 8/enterprise/Dockerfile
looks like i unintentionally duplicated some lines with the update of java and glibc that are not needed
> apply docker hub feedback

- 8/community/Dockerfile
- 8/developer/Dockerfile
- 8/enterprise/Dockerfile
> Release version to 8.6

- 8/community/Dockerfile
- 8/datacenter/app/Dockerfile
- 8/datacenter/search/Dockerfile
- 8/developer/Dockerfile
- 8/enterprise/Dockerfile
> Update Sonarqube to 8.7.0

- 8/community/Dockerfile
- 8/datacenter/app/Dockerfile
- 8/datacenter/app/run.sh
- 8/datacenter/search/Dockerfile
- 8/datacenter/search/run.sh
- 8/developer/Dockerfile
- 8/enterprise/Dockerfile
and fixed wrong JAVA_VERSION env
> rewrite ip detection

- release.md
Reorder the sections, to make clear that the documentation PR needs to be referenced in the other one.
> Update release documentation

- 7/community/Dockerfile
> Release 7.9.6

- 8/community/Dockerfile
- 8/developer/Dockerfile
- 8/enterprise/Dockerfile
> SONAR-14749 reduced the DNS cache validity from infinite to 5 seconds

- 8/community/Dockerfile
- 8/datacenter/app/Dockerfile
- 8/datacenter/search/Dockerfile
- 8/developer/Dockerfile
- 8/enterprise/Dockerfile
- 9/community/Dockerfile
- 9/datacenter/app/Dockerfile
- 9/datacenter/search/Dockerfile
- 9/developer/Dockerfile
- 9/enterprise/Dockerfile
> REL-1967 and REL-1966

- 9/community/Dockerfile
- 9/datacenter/app/Dockerfile
- 9/datacenter/search/Dockerfile
- 9/developer/Dockerfile
- 9/enterprise/Dockerfile
see statement here: https://github.com/docker-library/official-images/issues/10794
> SONAR-15344 Comply with new DockerHub enforcement

- 8/community/Dockerfile
- 8/datacenter/app/Dockerfile
- 8/datacenter/search/Dockerfile
- 8/developer/Dockerfile
- 8/enterprise/Dockerfile
> REL-2098 Release of 8.9.5.50698

- develop.md
- example-compose-files/sq-dce-postgres/docker-compose.yml
- example-compose-files/sq-with-h2/docker-compose.yml
- example-compose-files/sq-with-postgres/docker-compose.yml
- examples.md
> SONAR-15956 updated examples

- 8/community/Dockerfile
- 8/datacenter/app/Dockerfile
- 8/datacenter/search/Dockerfile
- 8/developer/Dockerfile
- 8/enterprise/Dockerfile
Alpine 3.12 will be EOL in 1 month and 3 weeks(01 May 2022)
> DOCKER-53 updated base image of LTS

- .github/workflows/qa.yml
- .github/workflows/release.yml
- 8/community/Dockerfile
- 8/datacenter/app/Dockerfile
- 8/datacenter/search/Dockerfile
- 8/developer/Dockerfile
- 8/enterprise/Dockerfile
- 9/community/Dockerfile
- 9/datacenter/app/Dockerfile
- 9/datacenter/search/Dockerfile
- 9/developer/Dockerfile
- 9/enterprise/Dockerfile
> BUILD-1450 SBOM

- example-compose-files/sq-with-postgres/docker-compose.yml
> Update Compose File - Environment Var DB is missing.

- example-compose-files/sq-with-postgres/docker-compose.yml
Name resolution not work with dinamic hostname and container_name
> Fix jdbc connection

- 9/community/Dockerfile
- 9/datacenter/app/Dockerfile
- 9/datacenter/search/Dockerfile
- 9/developer/Dockerfile
- 9/enterprise/Dockerfile
Bump base image version to get latest patches
> DOCKER-132 bump base image of Dockerfile

- 9/datacenter/search/run.sh
We set several properties which are not mandatory. This PR has the goal of cleaning them up.
> [NO-JIRA] Remove unnecessary properties setup

- .cirrus.yml
- run-tests.sh
> BUILD-3176 Use SonarSource CI infrastructure for tests

- .cirrus.yml
- 9/community/Dockerfile
- 9/datacenter/app/Dockerfile
- 9/datacenter/search/Dockerfile
- 9/developer/Dockerfile
- 9/enterprise/Dockerfile
> REL-2988 Upgrade LTS to 9.9.4.87374

- .cirrus/tasks.yml
- release.md
> SONAR-21908 Update mention from LTS to LTA

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/PullRequestClosed.yml
- .github/workflows/PullRequestCreated.yml
- .github/workflows/RequestReview.yml
- .github/workflows/SubmitReview.yml
[SONAR-23868](https://sonarsource.atlassian.net/browse/SONAR-23868)
The new YML are replacing the old `synchronize-jira.yml` (if present)
Make sure the files in the PR are the same as these
[PullRequestClosed.yml](https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/PullRequestClosed.yml)
[PullRequestCreated.yml](https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/PullRequestCreated.yml)
[RequestReview.yml](https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/RequestReview.yml)
[SubmitReview.yml](https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/SubmitReview.yml)
⚠️ Please make sure that `PullRequestCreated.yml` has the correct Jira project on the last line! …
> SONAR-23868 Add Jira integration

- .cirrus/tasks.yml
- 2025.1/datacenter/app/Dockerfile
- 2025.1/datacenter/search/Dockerfile
- 2025.1/developer/Dockerfile
- 2025.1/enterprise/Dockerfile
[REL-3507](https://sonarsource.atlassian.net/browse/REL-3507)
[REL-3507]: https://sonarsource.atlassian.net/browse/REL-3507?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> REL-3507 Release SonarQube Server 2025.1

- 2025.1/datacenter/app/Dockerfile
- 2025.1/datacenter/search/Dockerfile
- 2025.1/developer/Dockerfile
- 2025.1/enterprise/Dockerfile
[SONAR-24175](https://sonarsource.atlassian.net/browse/SONAR-24175)
[SONAR-24175]: https://sonarsource.atlassian.net/browse/SONAR-24175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONAR-24175 update base image to java 21

- .github/workflows/next-scan.yml
- .github/workflows/release-template.yml
- .github/workflows/slack_notify.yml
[SONAR-24331](https://sonarsource.atlassian.net/browse/SONAR-24331)
Part of SQDEVOPS-620
[SONAR-24331]: https://sonarsource.atlassian.net/browse/SONAR-24331?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONAR-24331 Updates CI tools

- example-compose-files/sq-with-postgres/docker-compose.yml
[SONAR-24451](https://sonarsource.atlassian.net/browse/SONAR-24451)
Duplicates #743 so we can run the CI.
[SONAR-24451]: https://sonarsource.atlassian.net/browse/SONAR-24451?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONAR-24451 Update postgres to version 17

- example-compose-files/sq-dce-custom-zip-postgres/Dockerfile-app
- example-compose-files/sq-dce-custom-zip-postgres/Dockerfile-search
- example-compose-files/sq-dce-custom-zip-postgres/README.md
- example-compose-files/sq-dce-custom-zip-postgres/docker-compose.yml
- example-compose-files/sq-dce-custom-zip-postgres/nginx.conf
- example-compose-files/sq-dce-custom-zip-postgres/run-app.sh
- example-compose-files/sq-dce-custom-zip-postgres/run-search.sh
- example-compose-files/sq-dce-custom-zip-postgres/unrestricted_client_body_size.conf
[SONAR-24314](https://sonarsource.atlassian.net/browse/SONAR-24314)
[SONAR-24314]: https://sonarsource.atlassian.net/browse/SONAR-24314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONAR-24314 Provide an example for using SonarQube Server DCE in docker

- .cirrus/tasks.yml
- community-build/Dockerfile
[REL-3592](https://sonarsource.atlassian.net/browse/REL-3592)
[REL-3592]: https://sonarsource.atlassian.net/browse/REL-3592?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> REL-3592 Release SonarQube Community Build 25.3

- 9/community/Dockerfile
- 9/datacenter/app/Dockerfile
- 9/datacenter/search/Dockerfile
- 9/developer/Dockerfile
- 9/enterprise/Dockerfile
[REL-3605](https://sonarsource.atlassian.net/browse/REL-3605)
[REL-3605]: https://sonarsource.atlassian.net/browse/REL-3605?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> REL-3605 Release SonarQube 9.9.9

- .cirrus/tasks.yml
[SONAR-24391](https://sonarsource.atlassian.net/browse/SONAR-24391)
[SONAR-24391]: https://sonarsource.atlassian.net/browse/SONAR-24391?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONAR-24391 Bumps LTA version for Cirrus

- 9/community/Dockerfile
- 9/developer/Dockerfile
[SONAR-24596](https://sonarsource.atlassian.net/browse/SONAR-24596)
[SONAR-24596]: https://sonarsource.atlassian.net/browse/SONAR-24596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONAR-24596 Release SonarQube 9.9.9 Enterprise and Data Center Editions

- .cirrus/tasks.yml
- 2025.1/datacenter/app/Dockerfile
- 2025.1/datacenter/search/Dockerfile
- 2025.1/developer/Dockerfile
- 2025.1/enterprise/Dockerfile
- 2025/datacenter/app/Dockerfile
- 2025/datacenter/search/Dockerfile
- 2025/developer/Dockerfile
- 2025/enterprise/Dockerfile
[REL-3609](https://sonarsource.atlassian.net/browse/REL-3609)
[REL-3609]: https://sonarsource.atlassian.net/browse/REL-3609?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> REL-3609 Release SonarQube Server 2025.1.1

- .cirrus/tasks.yml
- 2025/datacenter/app/Dockerfile
- 2025/datacenter/search/Dockerfile
- 2025/developer/Dockerfile
- 2025/enterprise/Dockerfile
[REL-3640](https://sonarsource.atlassian.net/browse/REL-3640)
[REL-3640]: https://sonarsource.atlassian.net/browse/REL-3640?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> REL-3640 Release SonarQube Server 2025.2.0

- 2025/datacenter/app/Dockerfile
- 2025/datacenter/search/Dockerfile
- 2025/developer/Dockerfile
- 2025/enterprise/Dockerfile
[REL-3640](https://sonarsource.atlassian.net/browse/REL-3640)
[REL-3640]: https://sonarsource.atlassian.net/browse/REL-3640?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> REL-3640 patch docker base image

- .github/workflows/release.yml
[REL-3640](https://sonarsource.atlassian.net/browse/REL-3640)
[REL-3640]: https://sonarsource.atlassian.net/browse/REL-3640?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> REL-3640 fix release sbom version

- .cirrus/tasks.yml
[SONAR-24760](https://sonarsource.atlassian.net/browse/SONAR-24760)
[SONAR-24760]: https://sonarsource.atlassian.net/browse/SONAR-24760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONAR-24760 Enable the full QA during our nightly job

- .cirrus/tasks.yml
- community-build/Dockerfile
[REL-3659](https://sonarsource.atlassian.net/browse/REL-3659)
[REL-3659]: https://sonarsource.atlassian.net/browse/REL-3659?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> REL-3659 Release SonarQube Community Build 25.4.0.105899

- .cirrus/tasks.yml
- community-build/Dockerfile
[REL-3710](https://sonarsource.atlassian.net/browse/REL-3710)
[REL-3710]: https://sonarsource.atlassian.net/browse/REL-3710?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> REL-3710 Release SonarQube Community Build 25.5

- example-compose-files/sq-dce-custom-zip-postgres/docker-compose.yml
- example-compose-files/sq-dce-postgres/docker-compose.yml
- example-compose-files/sq-with-postgres/docker-compose.yml
[SONAR-25084](https://sonarsource.atlassian.net/browse/SONAR-25084)
[SONAR-25084]: https://sonarsource.atlassian.net/browse/SONAR-25084?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONAR-25084 Feature/community/jc/trigger 767 fixing docker compose healthcheck

- .cirrus/tasks.yml
[SONAR-25081](https://sonarsource.atlassian.net/browse/SONAR-25081)
[SONAR-25081]: https://sonarsource.atlassian.net/browse/SONAR-25081?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONAR-25081 fix missing gcp push prod for LTA

- .cirrus/tasks.yml
- community-build/Dockerfile
[REL-3772](https://sonarsource.atlassian.net/browse/REL-3772)
[REL-3772]: https://sonarsource.atlassian.net/browse/REL-3772?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> REL-3772 Release SonarQube Community Build 25.6.0.109173

- renovate.json5
[SONAR-25277](https://sonarsource.atlassian.net/browse/SONAR-25277)
> SONAR-25277 add token for private release fetch

- docker-official-images/fixtures/active_versions.json
- docker-official-images/fixtures/docker-official-sonarqube
- docker-official-images/internal/build/build.go
- docker-official-images/official_images.tmpl
- release.md
- renovate.json5
[SONAR-25517](https://sonarsource.atlassian.net/browse/SONAR-25517)
[SONAR-25517]: https://sonarsource.atlassian.net/browse/SONAR-25517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONAR-25517 Update release.md, add GitFetch to official-image go release logic

- example-compose-files/sq-dce-postgres/docker-compose.yml
- example-compose-files/sq-with-postgres/docker-compose.yml
[SONAR-25775](https://sonarsource.atlassian.net/browse/SONAR-25775)
[SONAR-25775]: https://sonarsource.atlassian.net/browse/SONAR-25775?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONAR-25775 Fix the postgresql directory mounted in the examples

- .cirrus/tasks.yml
- .cirrus/wss-unified-agent.config
[SONAR-25897](https://sonarsource.atlassian.net/browse/SONAR-25897)
[SONAR-25897]: https://sonarsource.atlassian.net/browse/SONAR-25897?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONAR-25897 Remove Mend references in QA

- commercial-editions/datacenter/app/run.sh
- commercial-editions/datacenter/search/run.sh
- example-compose-files/sq-dce-custom-zip-postgres/run-app.sh
- example-compose-files/sq-dce-custom-zip-postgres/run-search.sh
[SONAR-25955](https://sonarsource.atlassian.net/browse/SONAR-25955)
[SONAR-25955]: https://sonarsource.atlassian.net/browse/SONAR-25955?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONAR-25955 fix quality fate by enclosing bash expensions
