- 4.5.4/Dockerfile
- 4.5.4/run.sh
- 5.1/Dockerfile
- 5.1/run.sh
- verify downloaded file PGP signatures (since signatures are available)
- reorder instructions a little for better cache overlap (shared layers between the two versions)
- utilize `WORKDIR` to make `run.sh` slightly simpler and allow the JSON syntax for `CMD` which avoids an extra `sh` process
- utilize `exec` in `run.sh` to avoid a second extra `sh` process (which makes `java` become "pid 1" in the container, instead of the shell -- see `docker top <running-container>`)
> Add a few minor tweaks

- 4.5.4/Dockerfile
- 5.1.1/Dockerfile
- 5.1/Dockerfile
Using Docker Compose, the plugins where uninstalled when using `docker-compose up` for the second time. Please see [this question on SO](http://stackoverflow.com/questions/31288681/sonar-qualityprofile-page-does-not-display-correctly-using-docker-when-data-volu/31324401).
Adding a VOLUME instruction also allows to do backups [like described in the docker documentation](https://docs.docker.com/userguide/dockervolumes/#backup-restore-or-migrate-data-volumes).
> Add VOLUME instruction to persist data and extentions.

- 5.1.1/Dockerfile
Use JDK as with JRE a NPE is raised upon chart generation e.g. when
viewing TimeMachine. Full Stack trace:
2015.07.14 20:56:34 ERROR web[o.s.s.c.ChartsServlet] Generating chart
org.sonar.server.charts.deprecated.SparkLinesChart
java.lang.NullPointerException: null
at sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264)
~[na:1.8.0_45-internal]
at
sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:219)
~[na:1.8.0_45-internal]
at sun.awt.FontConfiguration.init(FontConfiguration.java:107)
~[na:1.8.0_45-internal]
at
sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:776)
~[na:1.8.0_45-internal]
at sun.font.SunFontManager$2.run(SunFontManager.java:431)
~[na:1.8.0_45-internal]
at java.security.AccessController.doPrivileged(Native Method) …
> Fix NPE when Generating chart

- recipes.md
It is not necessary to expose postgresql port on host machine. Postgres will be accessible for the linked container(s) only.
The docker-compose starts postgres before sonar start.
> Use links instead of hacking

- 5.6.4-alpine/Dockerfile
- 5.6.4/Dockerfile
- 6.2-alpine/Dockerfile
- 6.2/Dockerfile
See https://github.com/docker-library/docs/pull/660/files#diff-5b18106a0a6d9cd97a6ecf2793c3347e (https://hub.docker.com/_/java/).
> Convert from "java" (deprecated as of 2016-12-31) to "openjdk"

- 5.6.6-alpine/Dockerfile
- 5.6.6/Dockerfile
- 6.3.1-alpine/Dockerfile
- 6.3.1/Dockerfile
maintainer is deprecated in release: v1.13.0
https://docs.docker.com/engine/deprecated/#repositoryshortid-image-references
I would like to make the change to label instead
> Remove deprecated MAINTAINER instruction

- 5.6.7-alpine/Dockerfile
- 5.6.7/Dockerfile
- 6.7.5-alpine/Dockerfile
- 6.7.5/Dockerfile
- 7.1-alpine/Dockerfile
- 7.1/Dockerfile
Fix the random failure while receiving GPG key. Error comes from SKS Keyservers high-availability pool containing some IPv6-only servers
nodejs/docker-node#380 
Fix by adding a conditional expression to fallback to the IPv4-only SKS pool if we get an IPv6 server from the high-availability pool.
> Fallback to IPv4 pool to fix keyserver receive failed

- 7.7-community/run.sh
Since the ldap properties are not starting with sonar. the env vars will be ignored.
https://docs.sonarqube.org/latest/instance-administration/delegated-auth/#header-2
> Add env support for ldap properties

- 8/community/Dockerfile
- 8/community/run.sh
**importante notice**
This PR only contains changes to the community edition Docker image. Changes will be exactly the same on Developer and Community edition images. To ease review and make it easier to apply  feedback, I only changed one image.
1. make sure volumes mounted to `conf` and `extensions` directories have content on initiale `docker run` call
- for Docker volumes created by the `docker run` call: initialization is handled by docker
- for existing empty volumes or empty bound host FileSystem directory: initialization is handled by entry point script (see `run.sh`)
- no initialization is performed by `run.sh` if mounted directory is not totally empty
2. remove declaration of volume from DockerFile because it didn't enforce anything related to usage of volumes with our image but …
> #322 Harden volume support

- 8/community/Dockerfile
- 8/community/run.sh
- 8/developer/Dockerfile
- 8/developer/run.sh
- 8/enterprise/Dockerfile
- 8/enterprise/run.sh
This PR fixes issue #323 
- this property was defined to make web process use /dev/urandom instead of /dev/random by setting env property `java.security.egd`
- there is no simple way set this property via `sonar.web.javaAdditionalOpts` and at the same time no overwrite `sonar.web.javaAdditionalOpts` defined in `sonar.properties`
- this has been worked around by setting `securerandom.source` at Java installation level (which affects all Java processes in the container) and not at all anymore at the SQ Web process level only
> fix sonar.properties properties ignored

- 8/community/run.sh
- 8/developer/run.sh
- 8/enterprise/run.sh
1. refer to the publicly know directory in logs instead of the non public one
2. display a message when not initializing the content of directories when "--init" option is used in docker run command
> improve init messages

- 8/community/Dockerfile
- 8/developer/Dockerfile
- 8/enterprise/Dockerfile
Using a single `RUN` command has a significant impact on the image size.
The following layers
```
e985a52a8e94        About a minute ago   |4 SONARQUBE_VERSION=8.0.0.29057 SONARQUBE_Z…   82B                 
1e9aca6a8b61        About a minute ago   /bin/bash -c #(nop)  USER sonarqube             0B                  
7aef49644565        About a minute ago   |4 SONARQUBE_VERSION=8.0.0.29057 SONARQUBE_Z…   352MB               
2e875e695a59        About a minute ago   |4 SONARQUBE_VERSION=8.0.0.29057 SONARQUBE_Z…   90.1MB              
9f3c4e0ec5ca        About a minute ago   |4 SONARQUBE_VERSION=8.0.0.29057 SONARQUBE_Z…   90.1MB              
4efa983381b8        About a minute ago   |4 SONARQUBE_VERSION=8.0.0.29057 SONARQUBE_Z…   262MB   
```
are replaced by the following single one:
``` …
```
> apply docker hub feedback

- .travis.yml
- 8/community/Dockerfile
- 8/developer/Dockerfile
- 8/enterprise/Dockerfile
This PR makes the last changes, to be merged into `branch-8`, needed to submit a valid PR to DockerHub for publication of the Docker image for SQ 8.0:
> remove all dogfood related code for SQ 8 images

- 7/community/Dockerfile
- 8/community/Dockerfile
- 8/developer/Dockerfile
- 8/enterprise/Dockerfile
The docker image currently does not allow the SVG badges plugin to be installed because that requires libfreetype and fontconfig.
Currently if you install the svg plugin in the docker image it will fail to start.
Added those to the Dockerfile and tested that the SVG plugin can be installed.
> SONAR-12696 Add libfreetype6 and libfontconfig1 for svg-badges

- 8/community/run.sh
- 8/developer/run.sh
- 8/enterprise/run.sh
Reason: typo in `run.sh` code for v8.
> Fix typos in run.sh for v8

- 8/community/Dockerfile
- 8/developer/Dockerfile
- 8/enterprise/Dockerfile
used upstream reference: https://github.com/AdoptOpenJDK/openjdk-docker/blob/master/11/jdk/alpine/Dockerfile.hotspot.releases.slim
also updated glibc as announced here: https://sourceware.org/pipermail/libc-announce/2020/000029.html
> updated java and glibc

- 9/community/Dockerfile
- 9/datacenter/app/Dockerfile
- 9/datacenter/search/Dockerfile
- 9/developer/Dockerfile
- 9/enterprise/Dockerfile
dogfood background portfolio recomputation failed over the weekend with `java.lang.UnsatisfiedLinkError: no fontmanager in java.library.path`  probably due to the headless jre not containing a fontmanager
> SONAR-15344 fontmanager missing in headless jre

- 8/community/Dockerfile
- 8/datacenter/app/Dockerfile
- 8/datacenter/search/Dockerfile
- 8/developer/Dockerfile
- 8/enterprise/Dockerfile
-  JRE download has moved from AdoptOpenJDK to Adoptium
- Updated JRE versions are available with various functional and secrity fixes
- `./run-tests.sh 8.9.6-community docker` yielded `8.9.6-community => success`
- Linux image tested with run-tests.sh
> Update jre versions

- README.md
Let's replace the status badge. We're not using Travis anymore, but use GitHub Actions.
> Replace status badge

- 9/community/Dockerfile
- 9/community/entrypoint.sh
- 9/developer/Dockerfile
- 9/developer/entrypoint.sh
- 9/enterprise/Dockerfile
- 9/enterprise/entrypoint.sh
- add entrypoint for compliance with [official-images](https://github.com/docker-library/official-images/tree/05f539b9a91128e2238f584d6dc4f0a81a8e1a9f#consistency)
- rework the way we add user to prevent belonging to `no_group`
- removing unneeded apt list after install
- revert changes made in #553, no longer required after tests on windows
> DOCKER-159 address docker hub maintainers comments

- 9/community/Dockerfile
- 9/datacenter/app/Dockerfile
- 9/datacenter/search/Dockerfile
- 9/developer/Dockerfile
- 9/enterprise/Dockerfile
Add the org.opencontainers.image.url label to the docker image.
These annotations are useful for people to manual use as well as for use by tools. For example, Snyk uses them in its UI and Renovate uses them to find release notes.
See: https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys
See: https://github.com/SonarSource/sonar-scanner-cli-docker/pull/160
---
> DOCKER-164: Add org.opencontainers.image.url label

- .cirrus.yml
Our image scanning tasks fail because of [this bug](https://bugs.launchpad.net/ubuntu/+source/ca-certificates-java/+bug/2019908). The quickest fix is to replace the OpenJDK used in the setup of those tasks.
> [NO JIRA] Replace bugged openjdk-17 used to scan our images

- 10/community/Dockerfile
- 10/datacenter/app/Dockerfile
- 10/datacenter/search/Dockerfile
- 10/developer/Dockerfile
- 10/enterprise/Dockerfile
As stated by docker official images maintainer, apt clean is not needed because the eclipse temurin base image uses hooks to every dpkg / apt command to clean afterward. Hence apt clean here is a no-op entry
> REL-3303 address reviewer comments removing no-op apt clean

- .cirrus/multi-arch-build.sh
- .cirrus/tasks.yml
- 2025.1/datacenter/app/Dockerfile
- 2025.1/datacenter/search/Dockerfile
- release.md
[SONAR-24200](https://sonarsource.atlassian.net/browse/SONAR-24200)
[SONAR-24200]: https://sonarsource.atlassian.net/browse/SONAR-24200?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONAR-24200 Fix the current versions used in the GCP images

- 2025.1/datacenter/app/Dockerfile
- 2025.1/datacenter/search/Dockerfile
- 2025.1/developer/Dockerfile
- 2025.1/enterprise/Dockerfile
- community-build/Dockerfile
- run-tests.sh
- tests/dce-compose-test/docker-compose.yml
[SONAR-24186](https://sonarsource.atlassian.net/browse/SONAR-24186)
We identified that we were not covering all options for runAsUser and runAsGroup in kubernetes context.
By adding ownership of files to sonarqube user we are compatible with both those workflow:
the current openshift behavior which is anyUid and gid=0
More classic use case were people rely on UID of the image (1000 in our case) but with gid!=0
Those two workflow will work as permissions are assigned to both owner and group.
[SONAR-24186]: https://sonarsource.atlassian.net/browse/SONAR-24186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONAR-24186 improve file ownership

- .cirrus/tasks.yml
- 2025/datacenter/app/Dockerfile
- 2025/datacenter/app/run.sh
- 2025/datacenter/app/sonar.sh
- 2025/datacenter/search/Dockerfile
- 2025/datacenter/search/run.sh
- 2025/datacenter/search/sonar.sh
- 2025/developer/Dockerfile
- 2025/developer/entrypoint.sh
- 2025/enterprise/Dockerfile
- 2025/enterprise/entrypoint.sh
[SONAR-24184](https://sonarsource.atlassian.net/browse/SONAR-24184)
[SONAR-24184]: https://sonarsource.atlassian.net/browse/SONAR-24184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONAR-24184 Define the structure for 2025.2.0 cycle

- .cirrus/multi-arch-build.sh
- .cirrus/tasks.yml
- 2025.1/datacenter/app/Dockerfile
- 2025.1/datacenter/search/Dockerfile
- 2025/datacenter/app/Dockerfile
- 2025/datacenter/search/Dockerfile
[SONAR-24220](https://sonarsource.atlassian.net/browse/SONAR-24220)
[SONAR-24220]: https://sonarsource.atlassian.net/browse/SONAR-24220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONAR-24220 Set a new GCP-Service-name annotation

- release.md
[SONAR-24325](https://sonarsource.atlassian.net/browse/SONAR-24325)
[SONAR-24325]: https://sonarsource.atlassian.net/browse/SONAR-24325?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONAR-24325 Documents how the released tag for the Docker image for Community Build must be

- community-build/Dockerfile
[SONAR-24570](https://sonarsource.atlassian.net/browse/SONAR-24570)
Part of SONAR-24175
[SONAR-24570]: https://sonarsource.atlassian.net/browse/SONAR-24570?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONAR-24570 Update the Community Build base image to use Java 21

- .github/workflows/PullRequestClosed.yml
- .github/workflows/RequestReview.yml
- .github/workflows/gcp-build-template.yml
- .github/workflows/mend-scan-template.yml
- .github/workflows/multi-arch-build-commercial-editions.yml
- .github/workflows/multi-arch-build-community-build.yml
- .github/workflows/multi-arch-build-template.yml
- .github/workflows/multi-arch-test-commercial-editions.yml
- .github/workflows/multi-arch-test-community-build.yml
- .github/workflows/multi-arch-test-template.yml
- .github/workflows/slack_notify.yml
- docker-official-images/active_versions.json
- docker-official-images/fixtures/active_versions.json
- docker-official-images/fixtures/docker-official-sonarqube
[BUILD-8875](https://sonarsource.atlassian.net/browse/BUILD-8875)
This PR updates GitHub Actions workflows to use our new standardized runner naming convention.
- Updates runner names in workflow files to new standardized format
- No functional changes to your CI/CD pipelines
- All existing functionality remains identical
| Old Runner | New Runner |
|------------|------------|
| sonar-runner-large | github-ubuntu-latest-s |
| ubuntu-latest-large | github-ubuntu-latest-s |
| windows-latest-large | github-windows-latest-s |
| ubuntu-24.04-large | github-ubuntu-latest-s |
| sonar-runner-large-arm | github-ubuntu-24.04-arm-s |
| ubuntu-24.04-arm-large | github-ubuntu-24.04-arm-s |
1. Review the changes in this PR
2. Merge when ready - no additional action required
3. Old runners will remain …
> BUILD-8875: Migrate to standardized GitHub runner names
